### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by anissen** [vujadin/BabylonHx_Snow#1]
This looks like an awesome project.

However, it really needs some information on how to run the tests and how to use it in the users own projects. It would also be nice if the project included a `project.flow` file such e.g. the test could be built & run with simply `flow run web` in the _test_ directory.

**Comment by vujadin** [comment]
Usage instructions added.

**Comment by anissen** [comment]
Thanks, it's works great! It would be cool if you could include, or link to, the assets that is used in the samples - right now the samples build and run but fail when the assets cannot be found.

**Comment by vujadin** [comment]
I've added link to Babylon.js samples repo, you'll find all required assets there.

**Comment by anissen** [comment]
Thanks :)
